packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@trpc/client": "^11.17.0"
  "@trpc/server": "^11.17.0"
  "@types/node": "^24.12.4"
  envin: "^1.2.0"
  typescript: "^6.0.3"
  valibot: "^1.4.0"

allowBuilds:
  "@nestjs/core": true
  "@prisma/engines": true
  "@swc/core": true
  better-sqlite3: false
  core-js: true
  esbuild: true
  libpq: true
  prisma: false
  sharp: true
